# Generated by Django 5.2.3 on 2025-06-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gravatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Gravatar URL'),
        ),
    ]
