# Generated by Django 5.2.3 on 2026-06-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gravatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gravatar_url',
        ),
    ]
