# Generated by Django 5.2.3 on 2025-07-15 15:38

import apps.batches.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0006_seed_recipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('batch_size', models.DecimalField(decimal_places=1, default=5.0, help_text='Gallons', max_digits=4, verbose_name='Batch Size (gal)')),
                ('og', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Original Gravity')),
                ('fg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Final Gravity')),
                ('primary_date', models.DateField()),
                ('secondary_date', models.DateField(blank=True, null=True)),
                ('bottling_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-primary_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.batches.models.batch_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='batches.batch')),
            ],
        ),
    ]
