# Generated by Django 5.2.3 on 2025-07-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='batchimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
