# Generated by Django 5.2.3 on 2025-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_batchimage_options_batchimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bottled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='bottled_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='create_must_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='create_must_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_1_3_break_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_1_3_break_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_24h_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_24h_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_48h_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_48h_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_72h_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_72h_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='pitch_yeast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='pitch_yeast_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='rack_secondary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='rack_secondary_done',
            field=models.BooleanField(default=False),
        ),
    ]
