# Generated by Django 5.2.3 on 2026-06-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_bottled_date_batch_bottled_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bottled_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='create_must_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_1_3_break_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_24h_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_48h_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='fo_72h_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='pitch_yeast_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batch',
            name='rack_secondary_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
