# Generated by Django 5.2.3 on 2026-06-10 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_batch_checklist_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aroma', models.TextField(blank=True)),
                ('flavor', models.TextField(blank=True)),
                ('overall', models.TextField(blank=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to='batches.batch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
