# Generated by Django 5.2.3 on 2026-06-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_add_tasting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='bottle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BottleConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='batches.batch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
