# apps/recipes/migrations/0002_auto_schema_changes.py
# Generated by Django 5.2.3 on 2025-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(
                choices=[
                    ('honey', 'Honey'),
                    ('yeast', 'Yeast'),
                    ('additive', 'Additive')
                ],
                default='honey',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(
                to='accounts.User',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                help_text='Null means global/seeded'
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='batch_size',
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                help_text='Gallons',
                max_digits=4
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(
                default='',
                help_text='Step-by-step instructions'
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(
                to='accounts.User',
                on_delete=models.CASCADE,
                null=True,
                blank=True,
                help_text='Null means global/seeded'
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(
                default='',
                help_text='e.g. ‘3 lbs’, ‘1 packet’',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

