# Generated by Django 5.2.3 on 2025-07-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_populate_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
    ]
